spring:
  application:
    name: todo-backend
  
  data:
    mongodb:
      uri: mongodb+srv://hson:Abc123456@cluster0.1prpbda.mongodb.net/?appName=Cluster0
      database: todoapp

server:
  port: ${PORT:8017}

jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25NdXN0QmVBdExlYXN0MjU2Qml0c0xvbmcxMjM0NTY3ODk=}
  expiration: 86400000
  refresh-expiration: 604800000

cors:
  allowed-origins: http://localhost:5173,http://192.168.1.23:5173,https://todolist-thuctap-nhom13.netlify.app
